### ISSUE TITLE
Compilation fails due deprecations

### ISSUE THREAD

**Issue by elhossary** [base4nfdi/website-template-hugo#13]
When compiling this template directly after cloning, it gives the following deprecation error:
```

WARN  deprecated: site config key paginate was deprecated in Hugo v0.128.0 and will be removed in a future release. Use pagination.pagerSize instead.
Start building sites … 
hugo v0.134.1+extended linux/amd64 BuildDate=unknown

ERROR deprecated: .Site.GoogleAnalytics was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.135.0. Use .Site.Config.Services.GoogleAnalytics.ID instead.



```
I cannot find this configuration, and It would be great to be fixed directly in the repo

**Comment by dlehmenk** [comment]
Currently the parent theme relies on a hugo version <=v0.121.1, there everything should work! but we will have a look at it regardless to be ready for future theme updates, thanks for bringing it up

**Comment by elhossary** [comment]
OK, I could find the cause. it is because of the Blox theme. They already fixed that 4 days ago, but still no module release that can be pulled from github during the build.
See:
https://github.com/HugoBlox/hugo-blox-builder/pull/3139
https://github.com/HugoBlox/hugo-blox-builder/pull/3137

**Comment by dlehmenk** [comment]
yeah, we've also to wait for HugoBlox/hugo-blox-builder#3135 before we can switch to a newer version, but as soon as these things are fixed will update

**Comment by dlehmenk** [comment]
close for now as we can't do something about this ourself now
